<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="MAIN" Id="{9753ee2a-e609-4081-882e-52e8c65681cc}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Getriebemotor: Getriebemotor;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Getriebemotor();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="14" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>